  char name[50];
    printf("Enter your name :");
    scanf("%s", &name);
    printf("\n\n");
    int deposit1;
    printf("Enter the amount of money to deposit for the game :");
    scanf("%d", &deposit1);
    printf("\n\n");
    printf("Your current balance is $%d", deposit1);
    printf("\n\n");
    int bet1;
    printf("%s, Enter the money to bet : $", name);
    scanf("%d", &bet1);
    printf("\n\n");
    if(bet1>deposit1)
