import Felgo 3.0
 import QtQuick 2.0

 GameWindow {
   id: gameWindow
    activeScene: scene
 Scene {
     id: scene
property int betAmount: 4 
     property int creditAmount: 400 
     Rectangle {
       anchors.fill: scene.gameWindowAnchorItem
       color: "#400000"
     }
   }
 }
